/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appletsalud;

/**
 *
 * @author Edwin
 */
public class JApplet extends javax.swing.JApplet {

    /**
     * Initializes the applet JApplet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kcalNormales = new javax.swing.JTextField();
        kcalGanar = new javax.swing.JTextField();
        kcalPerder = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        nivelActividad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        camina = new javax.swing.JLabel();
        nada = new javax.swing.JLabel();
        corre = new javax.swing.JLabel();
        cicle = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Datos personales");

        jLabel2.setText("Sexo:");

        jLabel3.setText("Altura (cm):");

        jLabel4.setText("Peso (kg):");

        jLabel5.setText("Edad:");

        altura.setName("altura"); // NOI18N

        peso.setName("peso"); // NOI18N

        edad.setName("edad"); // NOI18N

        jLabel6.setText("Resultados:");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nivel de actividad:");

        jLabel8.setText("Es la cantidad de calorias necesarias para mantener el peso.");

        jLabel9.setText("Son las calorias, debe consumir al día, para bajar 0.5kg de peso a la semana.");

        jLabel10.setText("Son las calorias que necesita al día para ganar 0.5kg a la semana.");

        jLabel13.setText("Sugerencia de ejercicios");

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        sexo.setName("sexo"); // NOI18N

        nivelActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nada de ejercicio", "Ejercicio 3-4 dias de la semana", "Ejercicio 5-6 dias a la semana" }));
        nivelActividad.setName("nivelActividad"); // NOI18N

        jLabel11.setText("Caminata");

        jLabel12.setText("Natación");

        jLabel14.setText("Correr");

        jLabel15.setText("Cliclismo");

        camina.setText("-");

        nada.setText("-");

        corre.setText("-");

        cicle.setText("-");

        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(kcalNormales, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kcalGanar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kcalPerder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(altura)
                                        .addComponent(sexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nivelActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(edad)
                                        .addComponent(peso))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(camina)
                            .addComponent(nada)
                            .addComponent(corre)
                            .addComponent(cicle))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(error)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivelActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kcalNormales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kcalGanar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kcalPerder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addComponent(camina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(1, 1, 1)
                .addComponent(nada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(corre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cicle)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Mujer = 665+(9.5 x peso)+(1.8 x altura)-(4.6 x edad)
        //Hombre = 66.4+(13.75 x peso)+(5 x altura)-(6.7 x edad) 
        //Caminar: 1.5, Nadar: 0.5, Correr: 0.75, Cicle: 1.75

        double alturaE = 0;
        double pesoE = 0;
        double edadE = 0;
        if (!altura.getText().equals("") && !peso.getText().equals("") && !edad.getText().equals("")) {
            alturaE = Double.parseDouble(altura.getText());
            pesoE = Double.parseDouble(altura.getText());
            edadE = Double.parseDouble(altura.getText());
            if (sexo.getSelectedIndex() == 0) {
                double caloriasTH = 0;
                if (nivelActividad.getSelectedIndex() == 0) {
                    caloriasTH = 1.2 * (66.4 + (13.75 * pesoE) + (5 * alturaE) - (6.7 * edadE));
                    kcalNormales.setText(String.valueOf(caloriasTH));
                    camina.setText(String.valueOf(caloriasTH / 1.5) + " calorias quemara en 30min de ejercicio al dia");
                    nada.setText(String.valueOf(caloriasTH / 0.5)  + " calorias quemara en 30min de ejercicio al dia");
                    corre.setText(String.valueOf(caloriasTH / 0.75)  + " calorias quemara en 30min de ejercicio al dia");
                    cicle.setText(String.valueOf(caloriasTH / 1.75)  + " calorias quemara en 30min de ejercicio al dia");
                }
                if (nivelActividad.getSelectedIndex() == 1) {
                    caloriasTH = 1.55 * (66.4 + (13.75 * pesoE) + (5 * alturaE) - (6.7 * edadE));
                    kcalNormales.setText(String.valueOf(caloriasTH));
                    camina.setText(String.valueOf(caloriasTH / 1.5)  + " calorias quemara en 30min de ejercicio al dia");
                    nada.setText(String.valueOf(caloriasTH / 0.5)  + " calorias quemara en 30min de ejercicio al dia");
                    corre.setText(String.valueOf(caloriasTH / 0.75)  + " calorias quemara en 30min de ejercicio al dia");
                    cicle.setText(String.valueOf(caloriasTH / 1.75)  + " calorias quemara en 30min de ejercicio al dia");
                }
                if (nivelActividad.getSelectedIndex() == 2) {
                    caloriasTH = 1.9 * (66.4 + (13.75 * pesoE) + (5 * alturaE) - (6.7 * edadE));
                    kcalNormales.setText(String.valueOf(caloriasTH));
                    camina.setText(String.valueOf(caloriasTH / 1.5)  + " calorias quemara en 30min de ejercicio al dia");
                    nada.setText(String.valueOf(caloriasTH / 0.5)  + " calorias quemara en 30min de ejercicio al dia");
                    corre.setText(String.valueOf(caloriasTH / 0.75)  + " calorias quemara en 30min de ejercicio al dia");
                    cicle.setText(String.valueOf(caloriasTH / 1.75)  + " calorias quemara en 30min de ejercicio al dia");
                }
            }
            if (sexo.getSelectedIndex() == 1) {
                double caloriasTM = 0;
                if (nivelActividad.getSelectedIndex() == 0) {
                    caloriasTM = 1.2 * (665 + (9.5 * pesoE) + (1.8 * alturaE) - (4.6 * edadE));
                    kcalNormales.setText(String.valueOf(caloriasTM));
                    camina.setText(String.valueOf(caloriasTM / 1.5)  + " calorias quemara en 30min de ejercicio al dia");
                    nada.setText(String.valueOf(caloriasTM / 0.5)  + " calorias quemara en 30min de ejercicio al dia");
                    corre.setText(String.valueOf(caloriasTM / 0.75)  + " calorias quemara en 30min de ejercicio al dia");
                    cicle.setText(String.valueOf(caloriasTM / 1.75)  + " calorias quemara en 30min de ejercicio al dia");
                }
                if (nivelActividad.getSelectedIndex() == 1) {
                    caloriasTM = 1.55 * (665 + (9.5 * pesoE) + (1.8 * alturaE) - (4.6 * edadE));
                    kcalNormales.setText(String.valueOf(caloriasTM));
                    camina.setText(String.valueOf(caloriasTM / 1.5)  + " calorias quemara en 30min de ejercicio al dia");
                    nada.setText(String.valueOf(caloriasTM / 0.5)  + " calorias quemara en 30min de ejercicio al dia");
                    corre.setText(String.valueOf(caloriasTM / 0.75)  + " calorias quemara en 30min de ejercicio al dia");
                    cicle.setText(String.valueOf(caloriasTM / 1.75)  + " calorias quemara en 30min de ejercicio al dia");
                }
                if (nivelActividad.getSelectedIndex() == 2) {
                    caloriasTM = 1.9 * (665 + (9.5 * pesoE) + (1.8 * alturaE) - (4.6 * edadE));
                    kcalNormales.setText(String.valueOf(caloriasTM));
                    camina.setText(String.valueOf(caloriasTM / 1.5)  + " calorias quemara en 30min de ejercicio al dia");
                    nada.setText(String.valueOf(caloriasTM / 0.5)  + " calorias quemara en 30min de ejercicio al dia");
                    corre.setText(String.valueOf(caloriasTM / 0.75)  + " calorias quemara en 30min de ejercicio al dia");
                    cicle.setText(String.valueOf(caloriasTM / 1.75)  + " calorias quemara en 30min de ejercicio al dia");
                }
            }
        } else {
            error.setText("No puedo calcular nada, faltan datos!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JLabel camina;
    private javax.swing.JLabel cicle;
    private javax.swing.JLabel corre;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField kcalGanar;
    private javax.swing.JTextField kcalNormales;
    private javax.swing.JTextField kcalPerder;
    private javax.swing.JLabel nada;
    private javax.swing.JComboBox<String> nivelActividad;
    private javax.swing.JTextField peso;
    private javax.swing.JComboBox<String> sexo;
    // End of variables declaration//GEN-END:variables
}
